import Foundation

/// Direction of a money movement.
/// `transfer` is neutral for global cash-flow but moves the balance between
/// two of the user's own accounts.
enum TransactionKind: String, Codable, CaseIterable, Identifiable {
    case income
    case expense
    case transfer

    var id: String { rawValue }
    var label: String {
        switch self {
        case .income:   return "Revenu"
        case .expense:  return "Dépense"
        case .transfer: return "Virement"
        }
    }
}

/// One financial movement, either manually entered by the user or generated
/// from a recurrence.
///
/// `amount` is **always** positive — the sign is derived from `kind`. This
/// keeps the data normalised and avoids ambiguity between "negative income"
/// and "expense".
struct Transaction: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    var date: Date

    /// Stored as an absolute value; the sign is determined by `kind`.
    var amount: Double

    var kind: TransactionKind
    var note: String = ""

    /// Owning account.
    var accountID: UUID?

    /// Optional category (nil for transfers and for uncategorised entries).
    var categoryID: UUID?

    /// Destination account when `kind == .transfer`.
    var transferTargetID: UUID?

    /// If non-nil, this transaction was auto-generated by a recurrence rule.
    /// Used for traceability ("show me everything Netflix produced").
    var sourceRecurrenceID: UUID?

    /// Contribution to global cash-flow (income − expense; transfers are neutral).
    var cashFlowImpact: Double {
        switch kind {
        case .income:   return amount
        case .expense:  return -amount
        case .transfer: return 0
        }
    }

    /// Effect of this transaction on a specific account's balance.
    /// Returns `0` if the transaction does not touch that account.
    func signedAmount(for accountID: UUID) -> Double {
        switch kind {
        case .income:   return self.accountID == accountID ?  amount : 0
        case .expense:  return self.accountID == accountID ? -amount : 0
        case .transfer:
            if transferTargetID == accountID { return  amount }
            if self.accountID    == accountID { return -amount }
            return 0
        }
    }
}
